[package]
name = "WrappedCoins"
version = "0.0.0"

[addresses]
std = "0x1"
wrapped_coins = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

# [dependencies.MoveStdlib]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/move-stdlib"
# rev = "aptos-node-v1.18.0"