[workspace]
members = ["aries"]
resolver = "3"

# this is needed for building aries package
[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin" }
# x25519-dalek = { git = "https://github.com/aptos-labs/x25519-dalek", branch = "zeroize_v1" }
