[package]
name = "AriesConfig"
version = "0.0.0"

[addresses]
aries_config = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"
# decimal = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

[dependencies]
Decimal = { local = "../decimal" }

# [dependencies.MoveStdlib]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/move-stdlib"
# rev = "main"

# [dependencies.AptosFramework]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/aptos-framework"
# rev = "main"

# [dependencies.AptosStdlib]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/aptos-stdlib"
# rev = "main"
