[package]
name = "Aries"
version = "0.0.0"

[addresses]
aries = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

[dev-addresses]

[dependencies]
AriesConfig = { local = "./aries-config" }
WrappedCoins = { local = "./wrapped-coins" }
Decimal = { local = "./decimal" }
Oracle = { local = "./oracle" }
# UtilTypes = { local = "./util-types" }
# HippoAggregator = {local = "./HippoAggregator"}

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
