[package]
name = "Aries"
version = "0.0.0"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aries = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

# Mainnet named addresses
hippo_aggregator = "0x890812a6bbe27dd59188ade3bbdbe40a544e6e104319b7ebc6617d3eb947ac07"

[dev-addresses]
aries = "0xeef200f2a06957a1548685c0feec9f1a04db27598fadab7f6daf30428fd064d3"

[dependencies]
UtilTypes = { local = "./util-types" }
# Oracle = { local = "../oracle" }
AriesConfig = { local = "./aries-config" }
WrappedCoins = { local = "./wrapped_coins" }
# Decimal = { local = "../decimal" }

# [dependencies.MoveStdlib]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/move-stdlib"
# rev = "aptos-node-v1.18.0"

# [dependencies.AptosFramework]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/aptos-framework"
# rev = "aptos-node-v1.18.0"

# [dependencies.AptosStdlib]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/aptos-stdlib"
# rev = "aptos-node-v1.18.0"

# [dependencies.HippoAggregator]
# git = "https://github.com/Aries-Markets/hippo-agg-interface.git"
# subdir = "."
# rev = "main"
