[package]
name = "moneyfi"
version = "1.0.0"
authors = []

[addresses]
moneyfi = "0xdc223ee5e19919d3f7f65c41d2dec698496e07b703a0575bc49b1615a1973b56"
stablecoin = "0xbae207659db88bea0cbead6da0ed00aac12edcdda169e591cd41c94180b46f3b"
[dev-addresses]

[dependencies.dex]
local = "hyperion-interface"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
