[package]
name = "ThalaV2RateLimiter"
version = "1.0.0"
authors = []

[addresses]
thala_v2_rate_limiter = "0x87978b35bf1eb73ae6cf04cfedcaa1f48254a683ebd00a21e7516a991edae3ac"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
