name: Contract Test

on:
  push:
    branches:
      - develop
    paths:
      - 'contracts/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'contracts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: ./contracts/setup.sh
      - uses: aptos-labs/actions/test-move@main
        with:
          WORKING_DIRECTORY: contracts
          ADDITIONAL_LINT_ARGS: --named-addresses moneyfi=0x123
          ADDITIONAL_COMPILE_ARGS: --named-addresses moneyfi=0x123
          ADDITIONAL_TEST_ARGS: --named-addresses moneyfi=0x123