name: Contract Test

on:
  push:
    branches:
      - develop
    paths:
      - 'contracts/**'
      - .github/workflows/move.yml
  pull_request:
    branches:
      - develop
    paths:
      - 'contracts/**'
      - .github/workflows/move.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aptos-labs/actions/install-aptos-cli@main
      - name: Setup
        run: ./contracts/setup.sh
      - uses: aptos-labs/actions/test-move@main
        with:
          SKIP_INSTALLING_CLI: 'true'
          SKIP_FMT: 'true'
          WORKING_DIRECTORY: contracts
          ADDITIONAL_LINT_ARGS: --named-addresses moneyfi=0x123
          ADDITIONAL_COMPILE_ARGS: --named-addresses moneyfi=0x123
          ADDITIONAL_TEST_ARGS: --named-addresses moneyfi=0x123